export type AnamneseData = {
  paciente?: string;
  profissao?: string;
  data_nasc?: string;
  sexo?: string;
  est_civil?: string;
  endereco?: string;
  cidade?: string;
  tel?: string;
  cel?: string;
  email?: string;
  indicado_por?: string;
  inicio_tratamento?: string;
  objetivo_consulta?: string;
  emergencia_nome?: string;
  emergencia_tel?: string;
  q01?: 'sim' | 'nao';
  q01_qual?: string;
  q01_detalhes?: string;
  q02?: 'sim' | 'nao';
  q02_qual?: string;
  q03?: 'sim' | 'nao';
  q03_qual?: string;
  q04?: 'sim' | 'nao';
  q04_obs?: string;
  q05?: 'sim' | 'nao';
  q05_qual?: string;
  q06?: 'sim' | 'nao';
  q06_qual?: string;
  q07_gestante?: 'sim' | 'nao';
  q07_filhos?: 'sim' | 'nao';
  q07_obs?: string;
  q08_pressao?: string;
  q08_coracao?: 'sim' | 'nao';
  q08_qual?: string;
  q09?: 'sim' | 'nao';
  q09_obs?: string;
  q10?: 'sim' | 'nao';
  q10_qual?: string;
  q11?: 'sim' | 'nao';
  q11_qual?: string;
  q12?: 'sim' | 'nao';
  q13?: 'sim' | 'nao';
  q14?: 'sim' | 'nao';
  observacoes?: string;
};
