// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const envMissing =
  !SUPABASE_URL ||
  !SUPABASE_PUBLISHABLE_KEY ||
  SUPABASE_URL === '' ||
  SUPABASE_PUBLISHABLE_KEY === '';

if (envMissing) {
  const msg =
    '[Supabase] Variáveis de ambiente ausentes. ' +
    'Local: crie um arquivo .env na raiz com VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY e reinicie o servidor (npm run dev). ' +
    'Deploy: defina essas variáveis no painel do provedor (Vercel, Netlify, etc.) e refaça o deploy.';
  console.error(msg);
  throw new Error(msg);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);