export { PatientDetailHeader } from './PatientDetailHeader';
export type { PatientDetailHeaderProps, PatientDetailPageTab } from './PatientDetailHeader';
export { PatientDetailNavTabs } from './PatientDetailNavTabs';
export { PatientPersonalInfoSection } from './PatientPersonalInfoSection';
export { PatientAnamneseSection } from './PatientAnamneseSection';
export type { AnamneseData } from '@/components/anamnese/anamneseTypes';
export { PatientLgpdSection } from './PatientLgpdSection';
export { PatientProceduresSection } from './PatientProceduresSection';
export { PatientSalonProceduresSection } from './PatientSalonProceduresSection';
export { PatientSalonRecurringAgendaSection } from './PatientSalonRecurringAgendaSection';
export { PatientExamsSection } from './PatientExamsSection';
export { PatientPrescriptionsSection } from './PatientPrescriptionsSection';
export { PatientDentalPlansSection } from './PatientDentalPlansSection';
export { PatientDocumentsSection } from './PatientDocumentsSection';
export { PatientDetailView } from './PatientDetailView';
export type { PatientDetailViewProps } from './PatientDetailView';
export { PatientDetailTabPanel, PatientTabPanelSection } from './PatientDetailTabPanel';
export { PatientTermTabSection } from './PatientTermTabSection';
export { SessionTimeline } from './SessionTimeline';
export type { SessionTimelineItem } from './SessionTimeline';
export { ActiveProcedureCard } from './ActiveProcedureCard';
export type { ActiveProcedureCardProps } from './ActiveProcedureCard';
export { CTASection } from './CTASection';
